# Generated by Django 6.0.3 on 2026-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bank', 'Bank Transfer')], db_index=True, max_length=20),
        ),
    ]
