# Generated by Django 6.0.3 on 2026-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_guest_address_order_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=8),
        ),
    ]
