# Generated by Django 6.0.3 on 2026-03-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_range',
            field=models.CharField(choices=[('4-5', '4–5 years'), ('5-6', '5–6 years'), ('6-7', '6–7 years'), ('7-8', '7–8 years'), ('8-9', '8–9 years'), ('9-10', '9–10 years'), ('10-11', '10–11 years'), ('11-12', '11–12 years'), ('12-13', '12–13 years'), ('13-14', '13–14 years'), ('14-15', '14–15 years')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('girls', 'Girls')], db_index=True, default='girls', max_length=10),
        ),
    ]
