# Generated by Django 6.0.3 on 2026-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_age_range_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_range',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Women'), ('girls', 'Girls'), ('unisex', 'Unisex')], db_index=True, default='women', max_length=10),
        ),
    ]
