# Generated by Django 6.0.3 on 2026-04-21 20:20

import cloudinary_storage.storage
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='products/', validators=[products.models.validate_file_size]),
        ),
    ]
